### PR TITLE
Web UI

### PR DESCRIPTION
**Pull request by xla**
This work started based on the hypothesis that an interface which follows the same design goals as the overall system can add immediate value for the brave who want to start using OK Log and might  convince the doubtful to not discard it completely. In order to get an understanding early on what might be important for such an interface I'm putting it out it in the open in a very experimental/rough state and hope to avoid spending energy non-effectively. Therefore everybody should feel encouraged to bring forth their ideas and needs regarding a web interface that interacts in (maybe rich ways) with large log volumes.

### Goals

* build a tool for users and operators of the system to interact with the dataset efficiently
* stay true to OK Logs operational simplicity
* encode/enforce best-practices and workflows for querying

### Non-Goals

* blindly copying other log tooling
* arguing for benefits or drawbacks of contemporary frontend technologies

### How to look at it?

Given you have access to this code branch, start up any of the stores (`oklog store`, `oklog ingeststore`) and point your browser to [/ui/](http://0.0.0.0:7650/ui/).

### Improvements

Achievable changes in this change-set.

- [x] simplify range controls
- [x] remove delay on stats query and fire on initialisation
- [x] support regex query
- [x] clarify planning output
- [ ] responsive ui design (media queries galore)
- [x] remove ULID column
- [x] move towards chunked consumption (possibly infinite scrolling)
- [ ] provide separate ui cmd
- [ ] encode query in URL for sharing

### CODE REVIEW

**Comment by danp** [comment]
Does this need to be built into oklog directly or could it be implemented externally using existing or possibly to-be-added api endpoints?

**Comment by peterbourgon** [comment]
> Does this need to be built into oklog directly or could it be implemented externally using existing or possibly to-be-added api endpoints?

I view a built-in web UI as a huge selling point for a nice out-of-the-box experience. It can compose nicely with other systems hooked in via other API endpoints.

**Comment by peterbourgon** [comment]
screen shot 2017-01-23 at 16 19 31

Played around with it, looks great! Feedback in no particular order.

- General model of floating query box over simple tabular output seems a perfect fit
- Highlighting query terms in output surprisingly effective
- Query planning section is precisely as envisioned, with some tweaks (see below)

Suggestions

- Probably need to return newest-to-oldest, but that should be managed in backend (#29)
- Lazy loading via typical infinite scroll techniques would be ideal, I can suggest how to do this
- ULID prefix provides no great value, its column can probably be removed
- Can make the statsOnly query with every change in the text box, even initially with 0 chars input
- "WINDOW: [1 hour|v] TO: [now|v]" could become even simpler "[1 hour ago|v]–[now|v]"
- Would be nice to have "treat as regex" checkbox, low prio
- If the query could be reflected in the URL, could enable easy sharing

Nits

- Floating box gets a bit wonky on smaller window sizes (see screenshot)
- The query planning is a bit misleading, those numbers actually mean "Your query will require reading a maximum of B bytes on each of N nodes, a total of approximately B*N bytes"

**Comment by xla** [comment]
> Does this need to be built into oklog directly or could it be implemented externally using existing or possibly to-be-added api endpoints?

@danp Have to second what @peterbourgon said. It shouldn't be orthogonal as the stores offer a straight-forward api, which are not too hard to consume. If there are existing tools which can work with variable data-sources (like grafana does for time-series data) everybody wins from driving the development of an OK Log source for such a tool forward.

Beyond the compelling argument of lower barrier to entry (think non-operators of the system) a native client can serve an entire different purpose. That is the constant validation of the offered APIs against real use-cases. Even with the little exploration in the beginning a lot of valuable additions/changes were discovered (#29, 4a84362). Which will continue to be the case.

**Comment by danp** [comment]
I'm totally in favor of a web UI, just not sold on it being bundled directly into oklog as it has much different concerns. For example, it's likely folks will want it to do many forms of authentication from integrating with N oauth providers to doing its own basic auth, etc.

Maybe `oklog ingeststore` or something like it could be the all-in-one version that runs ingest/store/ui but otherwise to get the ui you need to run `oklog ui`. Maybe that's what was already planned!

I think the api changes you mention would have been discovered just the same as if the UI was completely external to oklog.

**Comment by xla** [comment]
@peterbourgon Thanks for the feedback and glad that it seems to be in tune with your expectations.

Amended the PR descriptions with open points I think should be addressed before considering a merge. See some clarifying questions below.

> Probably need to return newest-to-oldest, but that should be managed in backend

Could the client order by ULID as a quick win?

> Lazy loading via typical infinite scroll techniques would be ideal, I can suggest how to do this

Huge room for improvement here as the client reads the entire response at the moment, which can kill the poor tabs. More than interested to hear your thoughts on this.

> ULID prefix provides no great value, its column can probably be removed

Had the same initial reaction and then it dawn on me that they could be used to reliable refer to a single log record, e.g. during collaborative forensics. As far as I can tell it's not possible to query for an ULID, was wondering if this is intended and if it should stay that way.

> The query planning is a bit misleading, those numbers actually mean "Your query will require reading a maximum of B bytes on each of N nodes, a total of approximately B*N bytes"

The value returned in `X-Oklog-Max-Data-Set-Size` is for a single node and that number should be multiplied by `X-Oklog-Nodes-Queried` to get the actual worst case amount of bytes, is that correct?

**Comment by xla** [comment]
@danp Thanks for clarifying as I understood **external** in your initial comment as not part of the oklog code-base.

> Maybe oklog ingeststore or something like it could be the all-in-one version that runs ingest/store/ui but otherwise to get the ui you need to run oklog ui. Maybe that's what was already planned!

Wasn't planned (at least form my side) but looks like a feasible route to take.

**Comment by peterbourgon** [comment]
>> Probably need to return newest-to-oldest, but that should be managed in backend
>
> Could the client order by ULID as a quick win?
>
>> Lazy loading via typical infinite scroll techniques would be ideal, I can suggest how to do this
>
> Huge room for improvement here as the client reads the entire response at the moment, which can kill the poor tabs. More than interested to hear your thoughts on this.

Yep, I think these two points get at the same issue, namely result set size is typically going to be huge, too much to load at once into the browser. Which makes your first point infeasible, and the second one important. Most sense is to make the query and read the first (say) 100 or 1000 records from the HTTP response. Only once the user scrolls down to the bottom of the viewport do you read the next (say) 10000 records, repeating as necessary.

The assumption here is that someone using the web UI is probably not gonna scroll all that much; unlike `oklog query` you can't compose these results into other tools. So if the user gets too many results they should likely further constrain the query than suffer through so many lines.

This strategy will be impacted by HTTP server timeouts and stuff—but I'd rather see how painful everything is in practice, before trying to over/engineer some sessions or query IDs, pagination, etc. etc.

>> ULID prefix provides no great value, its column can probably be removed
>
> Had the same initial reaction and then it dawned on me that they could be used to reliable refer to a single log record, e.g. during collaborative forensics. As far as I can tell it's not possible to query for an ULID, was wondering if this is intended and if it should stay that way.

Ah—this is quite interesting idea. Actually querying by a specific ULID should be easy and efficient, it's just like a range query with a really short range. Still I don't know how useful it would be in practice. It should be just as easy to copy/paste the log lines (copy by value) than to refer to it by ULID (copy by reference). Maybe I miss an interesting opportunity?

> The value returned in X-Oklog-Max-Data-Set-Size is for a single node and that number should be multiplied by X-Oklog-Nodes-Queried to get the actual worst case amount of bytes, is that correct?

Exactly correct. Hopefully this is precise enough for a query planner.

**Comment by peterbourgon** [comment]
> I'm totally in favor of a web UI, just not sold on it being bundled directly into oklog as it has much different concerns. For example, it's likely folks will want it to do many forms of authentication from integrating with N oauth providers to doing its own basic auth, etc.

The main advantage of colocating the UI on the store nodes is that they're already running an HTTP server with the API, so the UI already knows where the API is, it's already on localhost. If you move the UI to a separate set of processes, you have to find a way to tell them where the store nodes live, which probably means you're having the UI nodes join the cluster for peer discovery, which feels, I don't know, wasteful? — Could you say in a bit more detail what specific advantages a separate process for the UI would bring? Couldn't the security/auth concerns be externalized, and based on routes? I admit not much knowledge or experience for these types of things.

But it's not a big deal in the end. I reckon the code is pretty modular, the boundaries between process and component rather fluid. It would be easy to have a bool `-ui` flag on the `store` and `ingeststore` modes, with whatever defaults made sense. And then a separate `ui` mode altogether, with `-peer` flags to join up with the cluster.

**Comment by peterbourgon** [comment]
@xla That checklist looks great to me. I would happily merge with those things addressed.

**Comment by xla** [comment]
> Yep, I think these two points get at the same issue, namely result set size is typically going to be huge, too much to load at once into the browser. Which makes your first point infeasible, and the second one important. Most sense is to make the query and read the first (say) 100 or 1000 records from the HTTP response. Only once the user scrolls down to the bottom of the viewport do you read the next (say) 10000 records, repeating as necessary.

That strategy is sound. Question remains if there is enough control in the browser APIs for request handling to tune this behaviour. If efforts in that direction turn out to be futile I'd consider a handler provided under `/ui` which enables paging for the client. Not ideal by any means.

> Ah—this is quite interesting idea. Actually querying by a specific ULID should be easy and efficient, it's just like a range query with a really short range. Still I don't know how useful it would be in practice. It should be just as easy to copy/paste the log lines (copy by value) than to refer to it by ULID (copy by reference). Maybe I miss an interesting opportunity?

Copy by value is indeed a sensible replacement for my little use-case. Is the conclusion here that the user should not be exposed to ULIDs? If so I like to challenge the API returning them in the first place.

**Comment by peterbourgon** [comment]
> Is the conclusion here that the user should not be exposed to ULIDs? If so I like to challenge the API returning them in the first place.

Primary reason to leave them in is debug purposes. For example if you just dump `i++` to a forwarder as fast as you can, the results will be in random order within the minimum time granularity of ULIDs (1ms). Without the ULID prefix that can appear broken. — So I'd like to leave it in while we are still in a sort of alpha/beta phase, but absolutely long-term it's worth cutting.

> Question remains if there is enough control in the browser APIs for request handling to tune this behaviour. If efforts in that direction turn out to be futile I'd consider a handler provided under /ui which enables paging for the client. Not ideal by any means.

Yes please let me know. If it won't work in browser I'm not sure how to tackle it in the API. Thinking out loud: I'm strictly against any kind of session. Maybe we could hack a next_href style thing, use the last returned ULID as the new `&from=` timestamp, and have a byte or record `&limit=N`. Hmm. Potentially feasible.

**Comment by derekperkins** [comment]
> Probably need to return newest-to-oldest

Unless you're querying for a single log, I find that typically makes it much harder to read your logs.

**Comment by derekperkins** [comment]
In general, my biggest trouble with logging Web UIs is context. Oftentimes I'll be looking for a `panic` or something similar, and while a text search returns the panic line, it doesn't return the surrounding lines that contain the stacktrace. The best interface I've seen is Google Stackdriver logging, which allow you to do a top level grouping based on a request ID / zipkin style trace ID.

image

This might also help with the too much data problem, as you would only have to query a few top level columns, and only get all the log lines when the user drills into the grouping.

I realize that this is likely out of scope for now, but is incredibly valuable and may help to mitigate some of the other issues you are facing.

**Comment by peterbourgon** [comment]
> Unless you're querying for a single log, I find that typically makes it much harder to read your logs.

Really! This would be great news; reversing order turns out to be rather tricky ;)

> …context…

The main thing to consider is that OK Log is aggregating _all_ logs for a given domain (cluster, environment, whatever). I really like the idea of context like `grep -Cn` but would it still be useful if it's not scoped to something more specific?

**Comment by derekperkins** [comment]
> The main thing to consider is that OK Log is aggregating all logs for a given domain (cluster, environment, whatever).

That's why I brought up the grouping idea. If you could pass some grouping context to oklog, that should allow you to drill into the log regardless.

`mysql-cluster > slow-log > "my query"`
`some service > traceID > "panic query"`

**Comment by derekperkins** [comment]
Simpler yet would be a query option that says `+- N lines` that would include the surrounding N lines from the same ingest node. Not as fine-grained, but would work in a pinch.

**Comment by derekperkins** [comment]
> > Unless you're querying for a single log, I find that typically makes it much harder to read your logs.

> Really! This would be great news; reversing order turns out to be rather tricky ;)

That time is probably better spent on infinite scrolling / pagination, which IMO overcomes the flaws of not reversing the order.

**Comment by peterbourgon** [comment]
>  If you could pass some grouping context to oklog, that should allow you to drill into the log regardless.

This implies that OK Log would begin parsing the log lines, something I'm categorically against for the time being.

> Simpler yet would be a query option that says +- N lines that would include the surrounding N lines from the same ingest node. Not as fine-grained, but would work in a pinch.

What if it were +/- N lines from _any_ ingest node? Would it still be useful? (I'm guessing not really.)

**Comment by derekperkins** [comment]
> This implies that OK Log would begin parsing the log lines, something I'm categorically against for the time being...What if it were +/- N lines from any ingest node? Would it still be useful? (I'm guessing not really.)

What if `oklog` added a node ID (or even better a pod ID in k8s) as a prefix/suffix to the ULID? That would keep you from parsing the log output, while still narrowing the context to something more usable.

**Comment by derekperkins** [comment]
Maybe even just as an optional environment variable - `$OKLOG_NODE_ID`. If not set, it's either ignored or another auto-generated ID. That check only happens once, so it shouldn't impact throughput, while adding a very useful query filter.

**Comment by derekperkins** [comment]
Sorry for the multiple comments, I keep thinking I'm done with the thought, but then I'm not. Doing it with the env variable actually gives you multiple options for a Kubernetes type deployment (#13, #32). You run it as a DaemonSet if you just want node level context. You could also run `oklog ingest` as a sidecar container, with its own `$OKLOG_NODE_ID`, which you could choose a pod level ID as the "node ID", leaving `oklog` still deployment agnostic.

**Comment by peterbourgon** [comment]
You're talking about annotation. I really want that to be the job of your log forwarding pipeline, not the job of OK Log itself. For example, you could configure logspout or logstash to prepend this kind of information to each record, and use it instead of `oklog forward`.

**Comment by derekperkins** [comment]
I think that's fantastic.

For me, thinking about those annotations in the context of a Web UI is so that you could easily filter based on the prefix. This would let you treat the query system somewhat like Bigtable, with the prefixes essentially defining your primary key / most common query path.

**Comment by peterbourgon** [comment]
OK, let's reboot this effort. I'm giving [a talk at CloudNative Con on the 29th](https://cloudnativeeu2017.sched.com/event/9Tbq/go-microservices-go-kit-i-peter-bourgon-go-kit) and I'd love to showcase OK Log + web UI as a part of it.

I spoke with @xla a few days ago and we came up with a few things that need attention. Copying and updating the TODO list from above. (Some of these may be done already, let me know.)

- MVP
  - Rebase on current master
  - Simplify date selector: `[1 hour ago|v]–[now|v]`
  - Pagination or lazy-load/infinite-scroll support?
- Nice to have
  - Strip ULIDs
  - "Treat as regex" option
  - Get stats estimate after first char in textbox
  - More?
- Stretch goal: streaming query support
  - Is Transfer-Encoding: Chunked OK, or do we need SSE?
  - Append stuff to bottom, auto-scroll on new data
  - More?

@xla what's yer thinkin'?

**Comment by xla** [comment]
@peterbourgon Good plan and looking forward to a sneaky plug in your go-kit presentation. :p Commented inline to all the points and beyond that nothing we need to address urgently with this change-set.

> Rebase on current master

☑️ 

> Simplify date selector: [1 hour ago|v]–[now|v]

☑️ 

> Pagination or lazy-load/infinite-scroll support?

As we are limited from the client-side it would be very helpful if we can have API support for pagination, uni-directional and cursor based would work for now. I understand that we could use ULIDs naturally for that, but open to any other option and would follow with what the API dictates.

> Strip ULIDs

☑️ 

> "Treat as regex" option

*TODO*

> Get stats estimate after first char in textbox

☑️ 

> Stretch goal: streaming query support
> Is Transfer-Encoding: Chunked OK, or do we need SSE?

Needs investigation form my side, will get the low-hanging fruits out of the way first. Anything I should be aware of when testing or docs to look at?

> Append stuff to bottom, auto-scroll on new data

*TODO*

**Comment by peterbourgon** [comment]
> As we are limited from the client-side it would be very helpful if we can have API support for pagination, uni-directional and cursor based would work for now. I understand that we could use ULIDs naturally for that, but open to any other option and would follow with what the API dictates.

Can you describe how you see a typical query session going? User enters "foobar", click query, API returns some object with N results and a next page ULID? User scrolls to bottom, web UI makes second query with the ULID as a cursor?

> Needs investigation form my side, will get the low-hanging fruits out of the way first. Anything I should be aware of when testing or docs to look at?

Take a look at cmd/oklog/stream.go for the usage.

**Comment by xla** [comment]
> Can you describe how you see a typical query session going? User enters "foobar", click query, API returns some object with N results and a next page ULID? User scrolls to bottom, web UI makes second query with the ULID as a cursor?

Absolutely, ideally the API provides transparently the cursor to the next page that the client can pick up and might incidentally be a ULID. Alternatively the client could use the ULID of the last record returned, which might be more prone to break if the cursor implementation changes.

> Take a look at cmd/oklog/stream.go for the usage.

Tack! Will do.

**Comment by peterbourgon** [comment]
We just had a quick review session, and in the interests of getting an MVP merged and having a play, here's what I think are blockers:

- Add some smaller times to the From dropdown, e.g. 5m ago, 15m ago
- Wrap long lines with some indent
- "Treat as regex" checkbox

We'll boot up separate PRs for each of the following:

- Pagination via ULID cursors
- Separate `oklog ui` to a new command
- Add streaming support — will probably also bring the autoscroll feature

🍾

**Comment by xla** [comment]
- [ ] Add some smaller times to the From dropdown, e.g. 5m ago, 15m ago
- [ ] Wrap long lines with some indent
- [ ] "Treat as regex" checkbox
- [x] "Your query could return 123456789 Bytes…" → "…could return 123MB…"

**Pull request merged**
