### PR TITLE
[WIP] kubernetes helm chart.

### PR DESCRIPTION
**Pull request by kminehart**

### CODE REVIEW

**Comment by kminehart** [comment]
See #32

**Comment by jcftang** [comment]
JFTR, https://github.com/wehco/oklog/pull/1 following someones suggestion (above) exposing the pod ip to the instance of oklog makes everything *work*

**Comment by jcftang** [comment]
The chart probably needs a rethink, when the pods move about the ip address's can change (peers) and it cause the cluster to fail. I noticed this when I was testing various failure scenarios. It's probably not a good idea to encode the startup script too much in a config map.

**Comment by kminehart** [comment]
Yeah honestly, if you want to take this over, feel free to.  I don't see us using oklog just yet in our cluster, and so the development for this has kind of halted (as much as I'd love to finish it and contribute).

**Comment by peterbourgon** [comment]
See also https://github.com/pinpt/charts/tree/master/oklog

**Pull request closed without merging**
