### PR TITLE
Fix 'during recovery: rename data/store/74.....active 01...-01....flushed:  invalid cross-device link'

### PR DESCRIPTION
**Pull request by bkmit**
This patch fix oklog recovery after unclean shutdown when data stored on Docker volume.

### CODE REVIEW

**Comment by peterbourgon** [comment]
Oh, weird! Why did you close it? Can you dump a bit more info about the error?

**Comment by bkmit** [comment]
I'v closed PR because fix still under testing on my environment. Reopen when I'll be sure all is OK.

**Comment by bkmit** [comment]
Finally verified - fix works!
About problem detail - look like we are hit by https://github.com/moby/moby/issues/25409

**Comment by peterbourgon** [comment]
Neat, thanks!

**Pull request merged**
