### PR TITLE
Make store/ingeststore delay between reqests to ingester for next segment configurable using -store.segment-delay parameter.

### PR DESCRIPTION
**Pull request by bkmit**

### CODE REVIEW

**Comment by peterbourgon** [comment]
Happy to accept this, but curious what prompted it?

**Comment by bkmit** [comment]
I have small oklog cluster 1 ingeststore and 4 ingest nodes.
Each of nodes hosts 10 to 200 docker containers with different apps with logs forwarded to local oklog ingest node (CI test cluster).
Under heavy load ingest nodes start to collect many not forwadred segments.
After review of oklog code I have decided to play with some tuning of hardcoded values and made it runtime configurable.

**Comment by peterbourgon** [comment]
Are you setting it to a lower or higher duration?

**Comment by bkmit** [comment]
I have played with this delay value between 1 to 1000ms and count of consumers from 1 to 100. This changes has a liitle effect on segments gathering  from ingester nodes. 
But I think ability to configure this delay can be useful and made this PR.

**Pull request merged**
